# Overriding default paramerters. Helm Creates StatefulSets automatically
architecture: replicaset
replicaCount: 3
persistence:
    storageClass: "linode-block-storage"
auth:
    rootPassword: secret-root-pwd
    